-- MySQL Script generated by MySQL Workbench
-- wto, 23 cze 2015, 13:09:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `12_szafraniec` DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
USE `12_szafraniec` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `roles_blog` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` char(32) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `roles_blog` (`id`, `name`) VALUES
(1, 'ROLE_ADMIN'),
(2, 'ROLE_USER');

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `users_blog` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `login` char(32) COLLATE utf8_bin NOT NULL,
  `password` char(128) COLLATE utf8_bin NOT NULL,
  `role_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_users_1` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `users_blog`
  ADD CONSTRAINT `FK_users_2` FOREIGN KEY (`role_id`) REFERENCES `roles_blog` (`id`);

-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(160) COLLATE utf8_bin NOT NULL,
  `content` TEXT COLLATE utf8_bin NOT NULL,
  `date_published` DATE,
  `date_edited` DATE,
  `author` VARCHAR(20),
  `tags_id` VARCHAR(45),
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `posts` (`id`, `title`, `content`, `date_published`, `author`) VALUES
(1, 'Witajcie na superfajnym blogu!', ' Integer pulvinar mi a urna semper hendrerit. Nunc tristique dictum malesuada. Ut eget hendrerit nunc. Nunc ultricies pellentesque aliquet. Donec eros massa, faucibus placerat elit tincidunt, tincidunt gravida tortor. Fusce aliquam urna non augue maximus, id condimentum elit lobortis. Vivamus in malesuada neque. Pellentesque id vestibulum purus. Maecenas vel nulla sit amet ligula ultricies dignissim. Fusce varius neque lectus, ut vestibulum libero pharetra sit amet. Etiam faucibus neque ut posuere congue. Quisque dictum dui eu purus suscipit, ac aliquam erat pharetra. Ut ex sapien, lobortis vitae erat at, pellentesque aliquet lectus. Fusce diam risus, aliquet nec pretium ac, lacinia non mauris.', '23-06-2015', 'Marta'),
(2, 'Kolejny piękny dzień!', 'Nam ultrices lectus a euismod consequat. Duis egestas porttitor nibh, a bibendum dolor efficitur a. Maecenas pulvinar eget sapien quis pulvinar. Proin efficitur iaculis laoreet. Suspendisse id suscipit mauris. Nullam porttitor eleifend ante, a pharetra libero vehicula eu. Aliquam suscipit commodo mollis. Proin tincidunt hendrerit massa, ac mollis elit fringilla ut. Phasellus id nibh aliquet, auctor nulla quis, varius libero. Aliquam a magna vel libero tempus bibendum non sed felis. Vestibulum odio ipsum, iaculis et justo eu, suscipit dapibus mi. Nullam nec augue mollis, mattis orci ac, facilisis felis. Vestibulum ut convallis nunc, laoreet pharetra justo. Praesent posuere, nunc sit amet ornare maximus, massa neque porttitor arcu, et varius libero arcu iaculis nibh. Ut venenatis mauris hendrerit enim fringilla porttitor. Nulla sit amet sem congue, tincidunt lorem a, ullamcorper magna. Donec elementum faucibus laoreet. Suspendisse congue tristique lorem eu sollicitudin. In feugiat metus a erat lobortis viverra. Nulla dictum laoreet orci, vel aliquam nibh porttitor et. Vestibulum a leo mauris. In fringilla, magna et interdum faucibus, metus tortor interdum eros, eu laoreet nisi erat in urna. Donec dignissim, est id blandit molestie, libero nibh fermentum massa, sed mollis mauris lectus a ligula. Maecenas quis vehicula turpis, a vulputate risus. Cras quis nibh felis.', '23-06-2015', 'Marta'),
(3, 'Następny, jeszcze lepszy!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut accumsan elit. Maecenas quis suscipit risus. Sed suscipit leo ut condimentum consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin nec pulvinar orci. Suspendisse pulvinar cursus lectus vel facilisis. Duis at risus consectetur, imperdiet dui ut, scelerisque felis. Duis gravida, enim a bibendum facilisis, felis metus laoreet elit, vitae rhoncus justo urna id arcu. Aenean blandit urna massa. Phasellus libero urna, maximus at mollis sit amet, tincidunt et nisl. Sed placerat imperdiet tempus. Cras quis posuere ex. Curabitur in blandit mauris. Pellentesque eleifend scelerisque luctus. Nulla facilisi. Proin pharetra tortor non odio egestas cursus.', '23-06-2015', 'Marta'),
(4, 'Dziś trochę gorszy, ale nie tracimy humoru!', 'Donec laoreet turpis aliquam arcu malesuada, nec aliquam sem egestas. Praesent eget ante est. Etiam ultrices magna felis, eget posuere ipsum commodo ac. Curabitur blandit hendrerit ligula, sed maximus lectus semper eu. Sed at tristique augue. Aliquam dui lectus, vestibulum sed fringilla eu, semper vel ipsum. In malesuada imperdiet magna in bibendum. Duis nec sapien consectetur, condimentum dui ultricies, fringilla augue. Suspendisse erat mauris, venenatis nec erat et, posuere egestas mauris. Phasellus non est porta, dictum lectus et, posuere sapien.', '23-06-2015', 'Marta'),
(5, 'Dobra, dziś już bez przesady...', 'Nie ma tu nic :(', '23-06-2015', 'Marta'),
(6, 'OMG, nie mam w sobie tyle optymizmu.', 'Tu też nic nie ma, bo i tak nikt nie czyta Lorem ipsum...', '23-06-2015', 'Marta'),
(7, '... no dobra, jeszcze jeden post!', 'Saturday Night Fever', '23-06-2015', 'Marta'),
(8, 'No i ostatni! :)', 'Lorem ipsum sratatata :)', '23-06-2015', 'Marta');

-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `tags` (`id`, `name`) VALUES
 (1, 'styl życia'),
 (2, 'przepisy'),
 (3, 'uroda');


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `comment` TEXT NOT NULL,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `comments` (`id`, `date`, `comment`, `posts_id`, `users_id`) VALUES
 (1, '23-06-2015', 'Super post!', 1, 1),
 (2, '23-06-2015', 'Super post! Naprawdę fajny', 1, 2),
 (3, '23-06-2015', 'Super post! Super post!', 1, 2),
 (4, '23-06-2015', 'Super post! 123455677', 1, 1),
 (5, '23-06-2015', 'Lorem ipsum! Super post!', 1, 2),
 (6, '23-06-2015', 'Super post! Donec laoreet turpis aliquam arcu malesuada', 1, 1),
 (7, '23-06-2015', 'Donec laoreet turpis aliquam arcu malesuada Super post!', 1, 1);

-- -----------------------------------------------------
-- Table `mydb`.`posts_has_many_tags`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `posts_has_many_tags` (
  `id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`number_of_visitors`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `number_of_visitors` (
  `id` INT NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
